@baseUrl = http://localhost:3005
@username = yassine
@password = yassine

### Create User (Public)
# Expected: 201 Created
# Response: {"id": "xx", "username": "{{username}}"}
POST {{baseUrl}}/users
Content-Type: application/json
{
    "username": "{{username}}",
    "password": "{{password}}"
}

### Get All Users (Protected)
# Expected: 200 OK
GET {{baseUrl}}/users
Authorization: Basic {{username}} {{password}}

### Invalid credentials
# Expected: 401 Unauthorized
# Response: {"error": "Unauthorized. Invalid credentials"}
GET {{baseUrl}}/users
Authorization: Basic test test

### No credentials
# Expected: 401 Unauthorized
# Response: {"error": "Unauthorized. No credentials provided"}
GET {{baseUrl}}/users

### Get User by ID (Protected)
GET {{baseUrl}}/users/1
Authorization: Basic {{username}} {{password}}

### Get Users by Name (Protected)
GET {{baseUrl}}/users?username=yassine
Authorization: Basic {{username}} {{password}}


### health check
# Expected: 200 OK
GET {{baseUrl}}/health

### Delete User by ID (Protected)
DELETE {{baseUrl}}/users/17
Authorization: Basic {{username}} {{password}}
